// <auto-generated />
using System;
using HR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721170630_AddDeviceSyncTask")]
    partial class AddDeviceSyncTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Domain.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIP")
                        .HasColumnType("text");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("LogsType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PunchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PunchType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIP");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserInfoId", "Time")
                        .IsUnique();

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("HR.Domain.Entities.AttendanceShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("LateThreshold")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AttendanceShifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2425),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsDeleted = false,
                            Name = "Normal Shift",
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("HR.Domain.Entities.BonusRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessedByHrId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestingManagerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByHrId");

                    b.HasIndex("RequestingManagerId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("BonusRequests");
                });

            modelBuilder.Entity("HR.Domain.Entities.DailyAttendanceSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeductedDays")
                        .HasColumnType("numeric");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeductionApplied")
                        .HasColumnType("boolean");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TimeIn")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("TimeOut")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId", "Date")
                        .IsUnique();

                    b.ToTable("DailyAttendanceSummaries");
                });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HR.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HR.Domain.Entities.DeviceSyncTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("DeviceSyncTasks");
                });

            modelBuilder.Entity("HR.Domain.Entities.Fingerprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeviceUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FingerIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Template")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("TemplateSize")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIp");

                    b.HasIndex("DeviceUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("DeviceUserId", "FingerIndex", "DeviceIp")
                        .IsUnique();

                    b.ToTable("Fingerprints");
                });

            modelBuilder.Entity("HR.Domain.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("HR.Domain.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAllowed")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("HR.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedByHRAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByHRId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedByManagerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByManagerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedBySecondLineManagerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBySecondLineManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("HrComment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("text");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RejectedById")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByHRId");

                    b.HasIndex("ApprovedByManagerId");

                    b.HasIndex("ApprovedBySecondLineManagerId");

                    b.HasIndex("RejectedById");

                    b.HasIndex("RequestedShiftId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HR.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HR.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserInfoId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HR.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("HR.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Section", "Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2193),
                            Description = "Default work start time",
                            Key = "workDayStart",
                            Section = "Work",
                            Value = "08:30"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Default work end time",
                            Key = "workDayEnd",
                            Section = "Work",
                            Value = "16:00"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2200),
                            Description = "Required daily work hours",
                            Key = "requiredDailyHours",
                            Section = "Work",
                            Value = "8"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2202),
                            Description = "Default working days per month",
                            Key = "workingDaysPerMonth",
                            Section = "Work",
                            Value = "26"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2203),
                            Description = "Default allowed monthly leave days",
                            Key = "allowedMonthlyLeaveDays",
                            Section = "Work",
                            Value = "1.7"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2204),
                            Description = "Default allowed monthly leave hours",
                            Key = "allowedMonthlyLeaveHours",
                            Section = "Work",
                            Value = "4"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2206),
                            Description = "Default allowed yearly sick leave days",
                            Key = "allowedSickLeaveDays",
                            Section = "Work",
                            Value = "15"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 21, 17, 6, 29, 461, DateTimeKind.Utc).AddTicks(2207),
                            Description = "First day of week (0=Sunday, 6=Saturday)",
                            Key = "firstDayOfWeek",
                            Section = "Work",
                            Value = "6"
                        });
                });

            modelBuilder.Entity("HR.Domain.Entities.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("ZkEnrollNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("HR.Domain.Entities.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatus")
                        .HasColumnType("text");

                    b.Property<int>("ActualAlreadyTakenLeaves")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("AttendanceShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("AuthenticatorSecretKey")
                        .HasColumnType("text");

                    b.Property<string>("BiometricId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Card")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentOtp")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceIp")
                        .HasColumnType("text");

                    b.Property<int?>("DirectManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("EducationalLevel")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactRelation")
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameArabic")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is2FAEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSyncedToDevice")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OvertimeBalanceHours")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("text");

                    b.Property<string>("PersonalPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ReportToId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondLineManagerId")
                        .HasColumnType("integer");

                    b.Property<int?>("SectionId")
                        .HasColumnType("integer");

                    b.Property<string>("ShiftType")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkLocation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceShiftId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectManagerId");

                    b.HasIndex("ReportToId");

                    b.HasIndex("SecondLineManagerId");

                    b.HasIndex("SectionId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("HR.Domain.Entities.AttendanceLog", b =>
                {
                    b.HasOne("HR.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.BonusRequest", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "ProcessedByHr")
                        .WithMany("ProcessedBonuses")
                        .HasForeignKey("ProcessedByHrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.UserInfo", "RequestingManager")
                        .WithMany("RequestedBonuses")
                        .HasForeignKey("RequestingManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.UserInfo", "TargetUser")
                        .WithMany("ReceivedBonuses")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessedByHr");

                    b.Navigation("RequestingManager");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("HR.Domain.Entities.DailyAttendanceSummary", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HR.Domain.Entities.DeviceSyncTask", b =>
                {
                    b.HasOne("HR.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.Fingerprint", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR.Domain.Entities.LeaveBalance", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "ApprovedByHR")
                        .WithMany()
                        .HasForeignKey("ApprovedByHRId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.UserInfo", "ApprovedByManager")
                        .WithMany()
                        .HasForeignKey("ApprovedByManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.UserInfo", "ApprovedBySecondLineManager")
                        .WithMany()
                        .HasForeignKey("ApprovedBySecondLineManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.UserInfo", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.AttendanceShift", "RequestedShift")
                        .WithMany()
                        .HasForeignKey("RequestedShiftId");

                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByHR");

                    b.Navigation("ApprovedByManager");

                    b.Navigation("ApprovedBySecondLineManager");

                    b.Navigation("RejectedBy");

                    b.Navigation("RequestedShift");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.Section", b =>
                {
                    b.HasOne("HR.Domain.Entities.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HR.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("HR.Domain.Entities.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.UserInfo", "UserInfo")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("HR.Domain.Entities.UserInfo", b =>
                {
                    b.HasOne("HR.Domain.Entities.AttendanceShift", "AttendanceShift")
                        .WithMany("Users")
                        .HasForeignKey("AttendanceShiftId");

                    b.HasOne("HR.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HR.Domain.Entities.UserInfo", "DirectManager")
                        .WithMany()
                        .HasForeignKey("DirectManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.UserInfo", "ReportTo")
                        .WithMany()
                        .HasForeignKey("ReportToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.UserInfo", "SecondLineManager")
                        .WithMany()
                        .HasForeignKey("SecondLineManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Domain.Entities.Section", "Section")
                        .WithMany("Employees")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttendanceShift");

                    b.Navigation("Department");

                    b.Navigation("DirectManager");

                    b.Navigation("ReportTo");

                    b.Navigation("SecondLineManager");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("HR.Domain.Entities.AttendanceShift", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HR.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("HR.Domain.Entities.Device", b =>
                {
                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("HR.Domain.Entities.Section", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HR.Domain.Entities.UserInfo", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Notifications");

                    b.Navigation("ProcessedBonuses");

                    b.Navigation("ReceivedBonuses");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RequestedBonuses");

                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
